#!/bin/sh

if [ -z "$DMENU" ] 
then 
	DMENU="dmenu -fn "monospace:size=10" -nb "#222222" -nf "#bbbbbb" -sb "#cc0000" -sf "#eeeeee" -i -f"
fi
app=$(cat $HOME/.config/apps | $DMENU -p "exec")
if [ ! -z "$app" ]
then
	$TERMINAL -e $app &
fi
