#!/bin/sh
# requirements : 
#	- dmenu

histfile="$HOME/.zhistory"
if [ -z $DMENU ] 
then 
	DMENU="dmenu -fn "monospace:size=10" -nb "#222222" -nf "#bbbbbb" -sb "#cc0000" -sf "#eeeeee" -i -f"
fi
$(tac $histfile | sed 's/:.*;//g' | $DMENU)
