#!/bin/sh
# requirements : 
#	- dmenu

histfile="$HOME/.zhistory"
if [ -z "$DMENU" ] 
then 
	DMENU="dmenu -fn "monospace:size=10" -nb "#222222" -nf "#bbbbbb" -sb "#cc0000" -sf "#eeeeee" -i -f"
fi
input=$(tac $histfile | $DMENU)
echo $input
$input &
if ! grep -x "$input" $histfile
then
	echo "$input" >> $histfile
fi
