#!/bin/sh

pdf_viewer=zathura
dmenu="dmenu -l 20 -fn "monospace:size=10" -nb "#222222" -nf "#bbbbbb" -sb "#5d6b31" -sf "#eeeeee" -i -f"
pdf_file=$(find $HOME/ -name "*.pdf" | $dmenu -p "Zathura")
if [ ! $pdf_file = "" ]
then
	$pdf_viewer $pdf_file
fi
