#!/bin/sh

dmenu="dmenu -fn "monospace:size=10" -nb "#222222" -nf "#bbbbbb" -sb "#5d6b31" -sf "#eeeeee" -i -f"
host=$(cat .ssh/config | grep "Host " | awk '{ print $2}' | $dmenu -p "ssh" )
if [ ! -z "$host" ]
then
	alacritty -e ssh $host &
fi
