#!/bin/sh

dmenu="dmenu -fn "monospace:size=10" -nb "#222222" -nf "#bbbbbb" -sb "#cc0000" -sf "#eeeeee" -i -f"
app=$(cat $HOME/.config/apps | $dmenu -p "exec")
if [ ! -z "$app" ]
then
	alacritty -e $app &
fi
