#!/bin/sh

if test ! -f /tmp/lol.mp4 
then
	youtube-dl "https://www.youtube.com/watch?v=YlXBpLjSSMc" -o /tmp/lol.mp4
fi	

for i in 1 2 3 4 5 6 7 8 9 
do
	speed=$( echo ".3\n.4\n.6\n1\n1\n1.5\n2" | shuf)
	echo $speed
	mpv /tmp/lol.mp4 -loop --speed=$speed > /dev/null &
	sleep .4
done
