#!/bin/bash

while [[ $# -ge 1 ]]; do
	case "${1}" in
		-p|--path)
			path="$2"
			if [ "$path" = "." ]
			then
				path=$(pwd)
				printf "path is $path\n"
			else
				printf "path is $path\n"
			fi
			files_only=true
			shift
		;;
	*)
		path="$1"
		;;
	esac
	shift
done

if [ -z $path ]
then
	printf "Please specify a folder with -p or --path\n"
else
	find $path -type d -exec echo {} \; -exec dsdir {} \;
fi
