#!/bin/sh

configfile="$HOME/.config/jwitch/config"
maindir="/tmp/jwitch"
jsondir="$maindir/json"
thumdir="$maindir/thumb"
selected="$maindir/selected"

if [ ! -f "$configfile" ]
then
	echo "Can't find config file"
	exit 0
fi

for dir in $maindir $jsondir $thumdir
do
	if [ -d $dir ]
	then
		rm -fr $dir/*
	else
		mkdir $dir
	fi
done

while read l
do
	curl -s -X GET 'https://api.twitch.tv/helix/search/channels?query='$l'&first=1' \
		-H 'client-id: z0414km6y5haw5tlapo5wnhsjymojb' \
		-H 'Authorization: Bearer 8uv2771xvwibmys7xqd885c25d0xs5' | jq '.' \
		> $jsondir/$l &
done < $configfile
wait

for file in $(ls $jsondir)
do
	live=$(cat $jsondir/$file | grep "is_live" | awk '{ print $2 }' | sed 's/[" ,]//g' )
	if [ $live = "true" ]
	then
		link=$(cat $jsondir/$file | grep "thumbnail_url" | awk '{ print $2 }' | sed 's/[" ,]//g')
		wget "$link" -O "$thumdir/$file" &
	fi
done
wait

cd $thumdir
sxiv -obtp * > $selected

while read s
do
	mpv --mute=yes -ytdl https://www.twitch.tv/$s &> /dev/null
done < $selected
