#!/bin/sh 

curl -s -X GET 'https://api.twitch.tv/helix/streams?language=fr&first=20' \
	-H 'client-id: z0414km6y5haw5tlapo5wnhsjymojb' \
	-H 'Authorization: Bearer 8uv2771xvwibmys7xqd885c25d0xs5' > /tmp/topstreams

cat /tmp/topstreams | jq '.' | grep "user_name" | awk '{ print $2 }' | sed 's/[", ]//g' > /tmp/namestreams
cat /tmp/topstreams | jq '.' | grep "thumbnail_url" | awk '{ print $2 }' | sed 's/[", ]//g' | sed 's/{width}/1920/g' | sed 's/{height}/1080/g' > /tmp/thumblink

nb=$(wc -l /tmp/namestreams | awk '{ print $1}')

if [ -d /tmp/thumb/ ]
then
	rm -fr /tmp/thumb/
	mkdir /tmp/thumb/
else
	mkdir /tmp/thumb/
fi

for i in $(seq $nb)
do
	link=$(sed -n ""$i"p" < /tmp/thumblink)
	name=$(sed -n ""$i"p" < /tmp/namestreams)

	wget -q "$link" -O "/tmp/thumb/$name"
done

cd /tmp/thumb
cat /tmp/namestreams | sxiv -oitp  > /tmp/names

while read l
do
	mpv --mute=yes "https://www.twitch.tv/$l" &> /dev/null
done < /tmp/names
