#!/bin/sh -e

# requirements
#	- mpv
#	- sxiv

configfile="$HOME/.config/jwitch/config"
maindir="$(mktemp -d /tmp/jwitch.XXXXX)"
jsondir="$(mktemp -d $maindir/XXXXX)"
thumdir="$(mktemp -d $maindir/XXXX)"
selected="$(mktemp $maindir/XXXX)"

[ -z "$CLIENTID" -o -z "$BEARERKEY" ] && echo "No key provided, can't curl the api" && exit 0
[ ! -f "$configfile" ] && echo "Can't find config file" && exit 0

while read l; do
	curl -s -X GET "https://api.twitch.tv/helix/search/channels?query=$l&first=1" \
		-H "client-id: $CLIENTID" \
		-H "Authorization: Bearer $BEARERKEY" | jq '.' \
		> $jsondir/$l &
done < $configfile ; wait

for file in $(ls $jsondir) ; do
	live=$(grep "is_live" "$jsondir/$file" | awk '{ print $2 }' | sed 's/[" ,]//g' )
	if [ $live = "true" ]; then
		link=$(grep "thumbnail_url" "$jsondir/$file" | awk '{ print $2 }' | sed 's/[" ,]//g')
		wget -q "$link" -O "$thumdir/$file" &
	fi
done; wait

cd $thumdir
sxiv -obtp * > $selected

while read s; do
	mpv --mute=yes -ytdl https://www.twitch.tv/$s &> /dev/null
done < $selected
