#!/bin/sh -e

# requirements
#	- mpv
#	- sxiv

maindir="$(mktemp -d /tmp/jwitch2.XXXXX)"
topstreams="$(mktemp $maindir/topstreams.js.XXXXX)"
names="$(mktemp $maindir/XXXXX)"
thumblink="$(mktemp $maindir/XXXXX)"
thumbdir="$(mktemp -d $maindir/XXXXX)"
selected="$(mktemp $maindir/XXXXX)"

[ -z "$CLIENTID" -o -z "$BEARERKEY" ] && echo "No key provided, can't curl the api" && exit 0

curl -s -X GET "https://api.twitch.tv/helix/streams?language=fr&first=40" \
	-H "client-id: $CLIENTID" \
	-H "Authorization: Bearer $BEARERKEY" > $topstreams

jq '.' $topstreams | grep "user_name" | awk '{ print $2 }' | sed 's/[", ]//g' > $names
jq '.' $topstreams | grep "thumbnail_url" | awk '{ print $2 }' | sed 's/[", ]//g' | sed 's/{width}/1920/g' | sed 's/{height}/1080/g' > $thumblink

nb=$(wc -l $names | awk '{ print $1}')

for i in $(seq $nb); do
	link=$(sed -n ""$i"p" < $thumblink)
	name=$(sed -n ""$i"p" < $names)
	wget -q "$link" -O "$thumbdir/$name"&
done; wait

cd $thumbdir
sxiv -obitp < $names > $selected 

while read l; do
	mpv --mute=yes "https://www.twitch.tv/$l" &> /dev/null
done < $selected
