#!/bin/sh -e

# requirements
#	- mpv
#	- sxiv

topstreams="/tmp/jwitch2/topstreams.js"
names="/tmp/jwitch2/names"
thumblink="/tmp/jwitch2/links"
thumbdir="/tmp/jwitch2/thumbs"
maindir="/tmp/jwitch2"
selected="/tmp/jwitch2/selected"

[ -z "$CLIENTID" -o -z "$BEARERKEY" ] && echo "No key provided, can't curl the api" && exit 0

for dir in $maindir $thumbdir; do
	[ -d $dir ] && rm -fr $dir/* || mkdir $dir
done

curl -s -X GET "https://api.twitch.tv/helix/streams?language=fr&first=40" \
	-H "client-id: $CLIENTID" \
	-H "Authorization: Bearer $BEARERKEY" > $topstreams

cat $topstreams | jq '.' | grep "user_name" | awk '{ print $2 }' | sed 's/[", ]//g' > $names
cat $topstreams | jq '.' | grep "thumbnail_url" | awk '{ print $2 }' | sed 's/[", ]//g' | sed 's/{width}/1920/g' | sed 's/{height}/1080/g' > $thumblink

nb=$(wc -l $names | awk '{ print $1}')

for i in $(seq $nb); do
	link=$(sed -n ""$i"p" < $thumblink)
	name=$(sed -n ""$i"p" < $names)
	wget -q "$link" -O "$thumbdir/$name"&
done; wait

cd $thumbdir
cat $names | sxiv -oitp  > $selected

while read l; do
	mpv --mute=yes "https://www.twitch.tv/$l" &> /dev/null
done < $selected
