#!/bin/sh

# requirements : 
#	- xclip
#	- maim
#	- sxiv
#	- dmenu

if [ -n "$1" ]
then 
	maim_command="maim -s"
else
	maim_command="maim"
fi

if [ -z $DMENU ] 
then 
	DMENU="dmenu -fn "monospace:size=10" -nb "#222222" -nf "#bbbbbb" -sb "#cc0000" -sf "#eeeeee" -i -f"
fi
search=$( printf "Screenshot\nPin\nGimp\nClipboard" | $DMENU -p "Screenshot")

case $search in
	"")
		exit 1
		;;
	Screenshot)
		name_file=$( printf "" | $DMENU -p "enter file name" )
		if [ -z $name_file ]; then
			name_file=$(date +%F-%T)
		fi
		$maim_command > $HOME/$name_file.png
		;;
	Pin)
		name_file=$(date +%F-%T)
		if [ ! -d /tmp/screenshot ]
		then 
			mkdir /tmp/screenshot
		fi
		file=/tmp/screenshot/$name_file.png
		$maim_command > $file
		sxiv -b -p $file &
		break
		;;
	Gimp)
		name_file=$(date +%F-%T)
		file=/tmp/$name_file.png
		$maim_command > $file
		if [ -e $file ]; then
			echo $file exists
			gimp $file &
		fi
		break
		;;
	Clipboard)
		$maim_command | xclip -selection clipboard -t image/png
		break
		;;
esac
