#!/bin/sh

filename='alacritty.yml'
cd $HOME/.config/alacritty/

size=$(grep "size:" $filename | awk '{print $2}' )
if [ "$size" = "12" ]
then
	sed "s/size: 12/size: 9/g" $filename > .tmp
	mv .tmp $filename
else
	sed "s/size: 9/size: 12/g" $filename > .tmp
	mv .tmp $filename
fi
