#!/bin/sh
# requirements : 
#	- dmenu

histfile="$HOME/.zhistory"
[ -z "$DMENU" ]  && DMENU="dmenu -fn "monospace:size=10" -nb "#222222" -nf "#bbbbbb" -sb "#cc0000" -sf "#eeeeee" -i -f"
input=$(tac $histfile | $DMENU)
echo $input
$input &
# add the new input to histfile if it's not already inside
! grep -x "$input" $histfile && echo "$input" >> $histfile
