#!/bin/sh

mutt_conf=$HOME/.config/mutt

if [ -z "$DMENU" ] 
then 
	DMENU="dmenu -fn "monospace:size=10" -nb "#222222" -nf "#bbbbbb" -sb "#cc0000" -sf "#eeeeee" -i -f"
fi

cmd="mutt -F $mutt_conf/$(ls $mutt_conf/ | $DMENU -p "vim")"
if [ -n "$cmd" ]
then
	$TERMINAL -e $cmd
fi
