#!/bin/sh

mutt_conf=$HOME/.config/mutt

[ -z "$DMENU" ]  && DMENU="dmenu -fn "monospace:size=10" -nb "#222222" -nf "#bbbbbb" -sb "#cc0000" -sf "#eeeeee" -i -f"

cmd="$(ls $mutt_conf/ | $DMENU -p "vim")"
[ -n "$cmd" ] && $TERMINAL -e mutt -F $mutt_conf/$cmd
