#!/bin/sh -e

# requirements : 
#	- xclip
#	- imagemagisk
#	- sxiv
#	- dmenu

[ -n "$1" ] && screeshot="import" || screeshot="imlib2_grab"

[ -z "$DMENU" ]  && DMENU="dmenu -fn "monospace:size=10" -nb "#222222" -nf "#bbbbbb" -sb "#cc0000" -sf "#eeeeee" -i -f"
search=$( printf "Screenshot\nPin\nGimp\nClipboard" | $DMENU -p "Screenshot")

case "$search" in
	"")
		exit 1
		;;
	Screenshot)
		name_file=$( printf "" | $DMENU -p "enter file name" )
		[ -z $name_file ] && name_file=$(date +%F-%T)
		$screeshot $HOME/$name_file.png
		;;
	Pin)
		name_file=$(date +%F-%T)
		[ ! -d /tmp/screenshot ] && mkdir /tmp/screenshot
		file=/tmp/screenshot/$name_file.png
		$screeshot $file
		sxiv -b -p $file &
		break
		;;
	Gimp)
		name_file=$(date +%F-%T)
		file=/tmp/$name_file.png
		$screeshot $file
		[ -e $file ] && gimp $file &
		break
		;;
	Clipboard)
		name_file=$(date +%F-%T)
		file=/tmp/$name_file.png
		$screeshot $file 
		xclip -selection clipboard -t image/png -i $file
		break
		;;
	*)
		$screeshot $HOME/"$search.png"
		;;
esac
