#!/bin/sh -e

# requirements : 
#	- xclip
#	- imagemagisk
#	- sxiv
#	- dmenu

if [ -n "$1" ]
then 
	screeshot="import"
else
	screeshot="import -window 0"
fi

if [ -z "$DMENU" ] 
then 
	DMENU="dmenu -fn "monospace:size=10" -nb "#222222" -nf "#bbbbbb" -sb "#cc0000" -sf "#eeeeee" -i -f"
fi
search=$( printf "Screenshot\nPin\nGimp\nClipboard" | $DMENU -p "Screenshot")

case $search in
	"")
		exit 1
		;;
	Screenshot)
		name_file=$( printf "" | $DMENU -p "enter file name" )
		if [ -z $name_file ]; then
			name_file=$(date +%F-%T)
		fi
		$screeshot $HOME/$name_file.png
		;;
	Pin)
		name_file=$(date +%F-%T)
		if [ ! -d /tmp/screenshot ]
		then 
			mkdir /tmp/screenshot
		fi
		file=/tmp/screenshot/$name_file.png
		$screeshot $file
		sxiv -b -p $file &
		break
		;;
	Gimp)
		name_file=$(date +%F-%T)
		file=/tmp/$name_file.png
		$screeshot $file
		if [ -e $file ]; then
			echo $file exists
			gimp $file &
		fi
		break
		;;
	Clipboard)
		name_file=$(date +%F-%T)
		file=/tmp/$name_file.png
		$screeshot $file 
		xclip -selection clipboard -t image/png -i $file
		break
		;;
esac
