#!/bin/sh -e

# requirements : 
#	- xclip
#	- imagemagisk
#	- sxiv
#	- dmenu

[ ! -d /tmp/screenshot ] && mkdir /tmp/screenshot
[ -n "$1" ] && screenshot="import" || screenshot="imlib2_grab"
[ -z "$DMENU" ] && DMENU="dmenu -fn "monospace:size=10" -nb "#222222" -nf "#bbbbbb" -sb "#cc0000" -sf "#eeeeee" -i -f"
search=$(printf "Screenshot\nPin\nGimp\nClipboard" | $DMENU -p "Screenshot")
date=$(date +%F-%T)
img="$(mktemp /tmp/screenshot/XXXXXXXXX.png)"

case "$search" in
	"")
		exit 1 ;;
	Screenshot)
		eval "$screenshot" "$img"
		input=$(printf "" | $DMENU -p "enter file name")
		[ -z "$input" ] && input=$date
		( echo "$input" | grep ".png\|.jpg\|.jpeg" ) || input=$input.png
		mv $img "$HOME/$input" 
		break ;;
	Pin)
		$screenshot $img
		sxiv -b -p $img &
		break ;;
	Gimp)
		$screenshot $img
		[ -e $img ] && gimp $img &
		break ;;
	Clipboard)
		$screenshot $img
		xclip -selection clipboard -t image/png -i $img
		break ;;
	*)
		( echo "$search" | grep ".png\|.jpg\|.jpeg" ) || date=$seach.png
		$screenshot $HOME/"$search" ;;
esac
