#!/bin/sh

[ -z "$DMENU" ] && DMENU="dmenu -fn "monospace:size=10" -nb "#222222" -nf "#bbbbbb" -sb "#cc0000" -sf "#eeeeee" -i -f"
host=$(cat .ssh/config | grep "Host " | awk '{ print $2}' | $DMENU -p "ssh" )
[ -n "$host" ] && $TERMINAL -e ssh $host &
