#!/bin/sh
# requirements : 
#	- xclip
#	- dmenu

case "$1" in
	brave)
		browser='brave'
		;;
	brave-tor)
		browser='brave --proxy-server="socks5://localhost:9050" --host-resolver-rules="MAP * ~NOTFOUND , EXCLUDE localhost"'
		;;
	firefox)
		browser='firefox'
		;;
	tor)
		browser="$HOME/download/tor-browser_en-US/Browser/./start-tor-browser --allow-remote"
		;;
	*)
		if [ -n "$BROWSER" ]
		then 
			browser="$BROWSER"
		else
			browser="firefox"
		fi
		;;
esac

[ -z "$DMENU" ]  && DMENU="dmenu -fn "monospace:size=10" -nb "#222222" -nf "#bbbbbb" -sb "#cc0000" -sf "#eeeeee" -i -f"

bookmarks="$HOME/.config/bookmarks"
input=$( grep -o "\[.*\]" $bookmarks | sed 's/[][]//g' | $DMENU -p "Web" )

[ -z "$input" ] && exit 0

[ "$input" = Paste ] && input=$(xclip -selection c -o)

# if input contains a dot or : and doesn't contain a space: suppose it's a link
if echo "$input" | grep "\\.\|:" | grep -v ' '
then
	eval $browser \"$input\"
	exit 0
fi

if ! grep -q "\[$input\]" "$bookmarks"
then 
	search=$input
	input="Web"
fi

link=$(grep "\[$input\]" "$bookmarks" | sed "s/.*$input] //g")

if grep -q "$input.*{}" "$bookmarks"
then
	if [ -z "$search" ]; then
		search=$(printf "" | $DMENU -p "$input")
		[ -z "$search" ] && exit 0
	fi
	link=$(echo "$link" | sed "s|{}|$search|")
	eval $browser \"$link\" &
else
	eval $browser \"$link\" &
fi
